//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAD_Project_Sprint_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_line_item
    {
        public int ser_id { get; set; }
        public int inv_line_id { get; set; }
        public int inv_hed_id { get; set; }
        public double ser_cost { get; set; }
    
        public virtual invoice invoice { get; set; }
        public virtual service service { get; set; }
    }
}
