//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAD_Project_Sprint_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_line
    {
        public int order_hed_id { get; set; }
        public int order_line_id { get; set; }
        public int ser_id { get; set; }
    
        public virtual order order { get; set; }
        public virtual service service { get; set; }
    }
}
